# Generated by Django 5.0.6 on 2024-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='C:/Users/s_karthick/OneDrive/Desktop/INTERNSHIP/django_project/new_project_server/static/images'),
        ),
    ]
