# Generated by Django 5.0.6 on 2024-06-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_alter_imageupload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
    ]
